DeclareGlobalFunction( "reg_Example" );
DeclareGlobalFunction( "thompsons_nfa" );
DeclareGlobalFunction( "literal_nfa" );
DeclareGlobalFunction( "concatenate_nfa" );
DeclareGlobalFunction( "question_nfa" );
DeclareGlobalFunction( "star_nfa" );
DeclareGlobalFunction( "union_nfa" );
DeclareGlobalFunction( "plus_nfa" );
DeclareGlobalFunction( "create_state" );
DeclareGlobalFunction( "simulate_nfa" );
DeclareGlobalFunction( "epsilon_transitions" );
DeclareGlobalFunction( "move_state" );
DeclareGlobalFunction( "convert_to_postfix" );
DeclareGlobalFunction( "is_operator" );
DeclareGlobalFunction( "precedence" );
DeclareGlobalFunction( "format_expression" );
DeclareGlobalFunction( "display_Automaton");
DeclareGlobalFunction( "text_Match" );